name: 'Setup SSH Agent'
description: 'Starts the ssh-agent with the provided SSH keys and adds github.com to the known hosts.'
author: 'yakuhzi'
inputs:
  ssh-public-key:
    description: 'Public SSH key to register in the SSH Agent'
    required: true
  ssh-private-key:
    description: 'Private SSH key to register in the SSH Agent'
    required: true
runs:
  using: 'node16'
  main: 'dist/main.js'
branding:
  color: 'yellow'
  icon: 'package'
